version: 2.1

description: |
  Experimenting with CircleCI Orbs, potentially for standard deployments.
  Some extra text goes here, with a multi-line description.

executors:
  default:
    docker:
      - image: ubuntu:latest
  awscli:
    docker:
      - image: cardboardci/awscli:latest

jobs:
  deploy-to-s3:
    parameters:
      bucket:
        description: 'The name of the s3 bucket'
        type: string
      namespace:
        description: 'The namespace of the file'
        type: string
    executor: awscli
    steps:
      - sync:
          bucket: <<parameters.bucket>>
          namespace: <<parameters.namespace>>